# Generated by Django 6.0.5 on 2026-06-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Ф. И. О."),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
        ),
    ]
