# Generated by Django 6.0.5 on 2026-07-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("email_messages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_time", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Не успешно")], max_length=20, verbose_name="Статус"
                    ),
                ),
                ("server_response", models.TextField(blank=True, verbose_name="Ответ почтового сервера")),
            ],
            options={
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_sent_at", models.DateTimeField(verbose_name="Дата и время начала")),
                ("end_at", models.DateTimeField(verbose_name="Дата и время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("partial", "Частично выполнена"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False, verbose_name="Отправлена")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_messages.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
    ]
