# Generated by Django 6.0.5 on 2026-07-08 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="clients.client", verbose_name="Получатели"),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status", "is_active", "is_sent"], name="mailings_ma_status_ff1638_idx"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["first_sent_at", "end_at"], name="mailings_ma_first_s_bf5ba1_idx"),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(fields=["mailing", "status"], name="mailings_ma_mailing_7787d0_idx"),
        ),
    ]
