# Generated by Django 6.0.5 on 2026-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailingattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Была ли отправка"),
        ),
    ]
