# Generated by Django 6.0.5 on 2026-06-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailing_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_sent_at",
            field=models.DateTimeField(verbose_name="Дата и время начала отправки"),
        ),
    ]
