# Generated by Django 6.0.5 on 2026-07-02 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0006_remove_mailing_is_sent_mailing_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
