# Generated by Django 6.0.5 on 2026-07-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_add_timestamps"),
        ("email_messages", "0003_add_timestamps"),
        ("mailings", "0007_mailing_created_at_mailing_is_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"ordering": ["-created_at"], "verbose_name": "Рассылка", "verbose_name_plural": "Рассылки"},
        ),
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["-attempt_time"],
                "verbose_name": "Попытка отправки",
                "verbose_name_plural": "Попытки отправки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Отправлена"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="email_messages.message", verbose_name="Сообщение"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(to="clients.client", verbose_name="Получатели"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("partial", "Частично выполнена"),
                    ("completed", "Завершена"),
                    ("failed", "Ошибка"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["status", "is_active", "is_sent"], name="mailings_ma_status_ff1638_idx"),
        ),
        migrations.AddIndex(
            model_name="mailing",
            index=models.Index(fields=["first_sent_at", "end_at"], name="mailings_ma_first_s_bf5ba1_idx"),
        ),
        migrations.AddIndex(
            model_name="mailingattempt",
            index=models.Index(fields=["mailing", "status"], name="mailings_ma_mailing_7787d0_idx"),
        ),
    ]
